sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t andreidobrinski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andreidobrinski/react-test npm test

after_success:
  - docker build -t andreidobrinski/multi-client ./client
  - docker build -t andreidobrinski/multi-nginx ./nginx
  - docker build -t andreidobrinski/multi-server ./server
  - docker build -t andreidobrinski/multi-worker ./worker
  # login to docker CLI
  # use env vars from travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker hub
  - docker push andreidobrinski/multi-client
  - docker push andreidobrinski/multi-nginx
  - docker push andreidobrinski/multi-server
  - docker push andreidobrinski/multi-worker
