sudo: required
language: generic
services:
  - docker

before_script: cd react-frontend

before_install:
  - docker build -t andreidobrinski/docker-course-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true andreidobrinski/docker-course-udemy npm run test
